spin_manifest_version = "1"
authors = ["pierrickc"]
description = ""
name = "rust-api01"
trigger = { type = "http", base = "/api" }
version = "0.1.0"

[[component]]
id = "rust-api01"
source = "rust_api01.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/FooBar"
[component.build]
command = "cargo build --target wasm32-wasi --release"

[[component]]
id = "echo"
source = {url = "https://echo.wasm"}
allowed_http_hosts = []
[component.trigger]
route = "/echo"
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "echo"
